In [1]:
import numpy as np
import pandas as pd
import scipy.stats as sps
import plotly.graph_objs as go

# Точечные оценки

In [2]:
n1 = 10
n2 = 1000
n_exp = 10

In [3]:
mean_1 = []
mean_2 = []
std_1 = []
std_2 = []
for _ in range(n_exp):
    x1 = sps.norm.rvs(loc=1, scale=1, size=n1)
    mean_1.append(x1.mean())
    std_1.append(x1.std(ddof=1))
    x2 = sps.norm.rvs(loc=1, scale=1, size=n2)
    mean_2.append(x2.mean())
    std_2.append(x2.std(ddof=1))

In [4]:
mean_1

[1.0046096918841787,
 1.0402767267980702,
 0.9090811948111851,
 0.9666520697533594,
 0.8376622409650535,
 0.1974845296119554,
 1.1011239549903677,
 0.7171635600478451,
 0.25946193876262746,
 0.568624306209244]

In [5]:
mean_2

[0.9595008679967182,
 0.9871611203222918,
 1.0098418794766268,
 0.9739403679479146,
 1.020275351964862,
 0.9796828244365213,
 0.9876080011212368,
 1.0020290366179445,
 0.9673357888555847,
 1.0626296771465022]

In [6]:
std_1

[1.6747210057168251,
 1.1423986131047301,
 0.9000983251143466,
 0.7004784154501905,
 1.2760344042704148,
 1.0808959214077447,
 1.2295275692667575,
 1.2488174973524582,
 0.8751997985588728,
 1.0960726864898742]

In [7]:
std_2

[1.0262106438525773,
 0.9948042581650377,
 0.9717656665366746,
 1.0033105302658205,
 1.0027232391731642,
 1.025535594081351,
 0.9967050071537641,
 1.0174426920096578,
 1.0129352819387267,
 1.044989372470361]

# Доверительные интервал

In [8]:
alpha = 0.05

n1 = 10
n2 = 1000
n_exp = 10000

In [9]:
# коэффициент
c = sps.norm.ppf(1 - alpha/2)

In [10]:
c

1.959963984540054

In [11]:
mean_1 = []
mean_2 = []
std_1 = []
std_2 = []
for _ in range(n_exp):
    x1 = sps.norm.rvs(loc=1, scale=1, size=n1)
    mean_1.append(x1.mean())
    std_1.append(x1.std(ddof=1))
    x2 = sps.norm.rvs(loc=1, scale=1, size=n2)
    mean_2.append(x2.mean())
    std_2.append(x2.std(ddof=1))
    
mean_1 = np.array(mean_1)
mean_2 = np.array(mean_2)
std_1 = np.array(std_1)
std_2 = np.array(std_2)

In [12]:
CI_1 = np.array(list(zip(mean_1 - c*std_1/np.sqrt(n1), mean_1 + c*std_1/np.sqrt(n1))))

In [13]:
CI_2 = np.array(list(zip(mean_2 - c*std_2/np.sqrt(n2), mean_2 + c*std_2/np.sqrt(n2))))

In [14]:
CI_1

array([[0.35451957, 1.21535742],
       [0.6245261 , 1.5002762 ],
       [0.48863088, 1.70857542],
       ...,
       [0.13284519, 1.05618526],
       [0.12926832, 1.14389349],
       [0.64585493, 1.83552151]])

In [15]:
CI_2

array([[0.89300667, 1.01453928],
       [0.94261026, 1.07047042],
       [0.95999503, 1.08659054],
       ...,
       [0.96653296, 1.08903598],
       [0.97692172, 1.10251881],
       [0.98689031, 1.11615554]])

In [16]:
df_ci_1 = pd.DataFrame(CI_1, columns=["left", "right"])
df_ci_1["contain_real_mean"] = 1
df_ci_1.loc[(1 < df_ci_1["left"]) | (1 > df_ci_1["right"]), "contain_real_mean"] = 0
df_ci_1["contain_real_mean"].sum() / df_ci_1["contain_real_mean"].shape[0] 

0.9179

In [17]:
df_ci_2 = pd.DataFrame(CI_2, columns=["left", "right"])
df_ci_2["contain_real_mean"] = 1
df_ci_2.loc[(1 < df_ci_2["left"]) | (1 > df_ci_2["right"]), "contain_real_mean"] = 0
df_ci_2["contain_real_mean"].sum() / df_ci_2["contain_real_mean"].shape[0] 

0.951

### Отрисовка

In [18]:
size = 1000

x1 = sps.norm.rvs(loc=1, scale=11.5, size=size)
mean_1 = x1.mean()
std_1 = x1.std(ddof=1)

x2 = sps.norm.rvs(loc=1.3, scale=1, size=size)
mean_2 = x2.mean()
std_2 = x2.std(ddof=1)
    
CI_1 = [mean_1 - c*std_1 / np.sqrt(size), mean_1 + c*std_1 / np.sqrt(size)]

CI_2 = [mean_2 - c*std_2 / np.sqrt(size), mean_2 + c*std_2 / np.sqrt(size)]

In [19]:
CI_1

[0.5350889163133017, 1.9213968697154877]

In [20]:
CI_2

[1.234317783231849, 1.3566395191726528]

In [21]:
fig = go.Figure()
fig.add_shape(type="rect",
    x0=CI_1[0], y0=1, x1=CI_1[1], y1=2,
    fillcolor="lavender",
)
fig.add_shape(type="rect",
    x0=CI_2[0], y0=0, x1=CI_2[1], y1=1,
    fillcolor="RoyalBlue",
)
fig.update_shapes(dict(xref='x', yref='y'))
fig.show()

## Уилсон

In [22]:
size = 1000

x1 = sps.bernoulli.rvs(p=0.015, size=size)
mean_1 = x1.mean()
std_1 = x1.std(ddof=1)

x2 = sps.bernoulli.rvs(p=0.025, size=size)
mean_2 = x2.mean()
std_2 = x2.std(ddof=1)
    
CI_1 = [mean_1 - c*std_1 / np.sqrt(size), mean_1 + c*std_1 / np.sqrt(size)]

CI_2 = [mean_2 - c*std_2 / np.sqrt(size), mean_2 + c*std_2 / np.sqrt(size)]

In [23]:
CI_1, CI_2

([0.008219224451177795, 0.023780775548822207],
 [0.01131852772587211, 0.02868147227412789])

In [24]:
z = sps.norm.ppf(1 - alpha/2)

In [25]:
CI_1_U = [(mean_1 + z**2 / (2*size) - z*np.sqrt(mean_1*(1-mean_1)/size + z**2/(4*size**2))) / (1 + z**2 / size),
          (mean_1 + z**2 / (2*size) + z*np.sqrt(mean_1*(1-mean_1)/size + z**2/(4*size**2))) / (1 + z**2 / size)]

In [26]:
CI_2_U = [(mean_2 + z**2 / (2*size) - z*np.sqrt(mean_2*(1-mean_2)/size + z**2/(4*size**2))) / (1 + z**2 / size),
          (mean_2 + z**2 / (2*size) + z*np.sqrt(mean_2*(1-mean_2)/size + z**2/(4*size**2))) / (1 + z**2 / size)]

In [27]:
CI_1_U, CI_2_U

([0.009872242002277388, 0.02583206021173997],
 [0.012983682916415135, 0.030690005229717782])

# Bootstrap

In [28]:
def get_bootstrap_sample_indices(sample_size: int, n_samples: int) -> np.ndarray:
    return np.random.randint(0, sample_size, (n_samples, sample_size))

def get_bootstrap_samples(X: np.ndarray, n_samples: int) -> np.ndarray:
    return X[get_bootstrap_sample_indices(len(X), n_samples)]

In [29]:
size = 100
x_a = sps.expon.rvs(loc=4, scale=16, size=size)

In [30]:
np.median(x_a)

16.458569775338695

In [32]:
X_bootstrap

array([[29.53969521, 20.46327977, 30.11165515, ...,  6.32136566,
        31.66347196,  8.08764498],
       [ 6.07213572, 19.74416463,  5.57793224, ...,  8.23489496,
        52.86578416, 12.56893931],
       [53.41937249, 21.82185389, 33.55999197, ...,  8.51262369,
        29.53969521, 45.41533577],
       ...,
       [29.53969521, 16.92915908, 19.53122185, ..., 12.33894029,
         8.30682958, 24.3100923 ],
       [ 8.23489496, 14.90222341, 26.85911373, ..., 33.55999197,
         6.41351587,  7.42535433],
       [30.11165515, 11.828276  , 12.9858527 , ..., 12.56893931,
        13.46468803, 15.2368392 ]])

In [33]:
metrics_mean = np.median(X_bootstrap, axis=1)

In [34]:
go.Figure([go.Histogram(x=metrics_mean)])

In [35]:
alpha = 0.05

In [36]:
CI = np.percentile(metrics_mean, (alpha * 100, (1 - alpha) * 100))

In [37]:
CI

array([13.85352946, 17.87156682])

# T-test

In [38]:
size = 30
n_sample = 1000
p_values = []
for _ in range(n_sample):
    x_a = sps.norm.rvs(loc=1, scale=11.5, size=size)
    x_b = sps.norm.rvs(loc=1, scale=1, size=size)
    p_values.append(sps.mannwhitneyu(x_a, x_b).pvalue)
p_values = np.array(p_values)

In [39]:
p_values[p_values < 0.05].shape[0] / n_sample

0.091

In [40]:
size = 30
n_sample = 1000
p_values = []
for _ in range(n_sample):
    x_a = sps.expon.rvs(loc=1, scale=1, size=size)
    x_b = sps.expon.rvs(loc=1, scale=1, size=size)
    p_values.append(sps.ttest_ind(x_a, x_b, equal_var=False).pvalue)
p_values = np.array(p_values)

In [41]:
p_values[p_values < 0.05].shape[0] / n_sample

0.046

# Манн-Уитни

In [42]:
x_a = [15, 12, 12, 10]
x_b = [14, 11, 9, 9]

In [43]:
sps.mannwhitneyu(x_a, x_b)

MannwhitneyuResult(statistic=12.0, pvalue=0.30649216504158383)

In [44]:
xr_a = [0, 2.5, 2.5, 5]
xr_b = [1, 4, 6.5, 6.5]

In [45]:
sps.ttest_ind(xr_a, xr_b)

Ttest_indResult(statistic=-1.2060453783110545, pvalue=0.2731950096793189)

In [46]:
size = 30
n_sample = 1000
p_values = []
for _ in range(n_sample):
    x_a = sps.norm.rvs(loc=1, scale=1, size=size)
    x_b = sps.norm.rvs(loc=1, scale=1, size=size)
    p_values.append(sps.mannwhitneyu(x_a, x_b).pvalue)
p_values = np.array(p_values)

In [47]:
p_values[p_values < 0.05].shape[0] / n_sample

0.047

In [1]:
size = 30
n_sample = 1000
p_values = []
for _ in range(n_sample):
    x_a = sps.expon.rvs(loc=1, scale=1, size=size)
    x_b = sps.expon.rvs(loc=1, scale=1, size=size)
    p_values.append(sps.mannwhitneyu(x_a, x_b).pvalue)
p_values = np.array(p_values)

NameError: name 'sps' is not defined

In [49]:
p_values[p_values < 0.05].shape[0] / n_sample

0.057

# Мощность критерия

In [50]:
size = 100
effect = 10
n_exp = 10_000
alpha = 0.05

p_values = []
for i in range(n_exp):
    x_a = sps.norm.rvs(loc=10, scale=3, size=size)
    x_b = sps.norm.rvs(loc=10 + effect, scale=3, size=size)
    p_value = sps.ttest_ind(x_a, x_b).pvalue
    p_values.append(p_value)
p_values = np.array(p_values)

Оценка мощности

In [51]:
p_values[p_values < alpha].shape[0] / p_values.shape[0] * 100

100.0

# Корректность критерия

Вариант с нормальными распределениями

In [52]:
p_values = []
size = 5
n_exp = 1000
for i in range(n_exp):
    x_a = sps.norm.rvs(loc=1, scale=1, size=size)
    x_b = sps.norm.rvs(loc=1, scale=1, size=size)
    p_value = sps.ttest_ind(x_a, x_b, equal_var=False).pvalue
    p_values.append(p_value)
p_values = np.array(p_values)

Вариант с смесью нормальных распределений

In [53]:
p_values = []
size = 100
n_exp = 10000
for i in range(n_exp):
    x_a = np.append(
        sps.norm.rvs(loc=1, scale=1, size=size),
        sps.norm.rvs(loc=0.5, scale=0.1, size=size),
    )
    x_b = np.append(
        sps.norm.rvs(loc=1, scale=1, size=size),
        sps.norm.rvs(loc=0.5, scale=0.1, size=size),
    )
    p_value = sps.ttest_ind(x_a, x_b).pvalue
    p_values.append(p_value)
p_values = np.array(p_values)

Другой вариант со смесью нормальных распеределений

In [54]:
p_values = []
size = 100
n_exp = 10000
for i in range(n_exp):
    a_1 = sps.norm.rvs(loc=1, scale=1, size=size)
    a_2 = sps.norm.rvs(loc=0.5, scale=0.1, size=size)
    a_mask = sps.randint.rvs(0, 2, size=size).astype(bool)
    x_a = np.append(
        a_1[a_mask],
        a_2[~a_mask],
    )
    
    b_1 = sps.norm.rvs(loc=1, scale=1, size=size)
    b_2 = sps.norm.rvs(loc=0.5, scale=0.1, size=size)
    b_mask = sps.randint.rvs(0, 2, size=size).astype(bool)
    x_b = np.append(
        b_1[b_mask],
        b_2[~b_mask],
    )
    p_value = sps.ttest_ind(x_a, x_b, equal_var=True).pvalue
    p_values.append(p_value)
p_values = np.array(p_values)

Экспоненциальные распределения

In [55]:
p_values = []
size = 15
n_exp = 10000
for i in range(n_exp):
    x_a = sps.expon.rvs(scale=1/2, size=size)
    x_b = sps.expon.rvs(scale=1/2, size=size)
    p_value = sps.ttest_ind(x_a, x_b).pvalue
    p_values.append(p_value)
p_values = np.array(p_values)

Бернулли распределение

In [56]:
p_values = []
size = 1000
n_exp = 10000
for i in range(n_exp):
    x_a = sps.bernoulli.rvs(p=0.05, size=size)
    x_b = sps.bernoulli.rvs(p=0.05, size=size)
    p_value = sps.ttest_ind(x_a, x_b).pvalue
    p_values.append(p_value)
p_values = np.array(p_values)

### Оценка распределения

In [57]:
fig = go.Figure([go.Histogram(x=x_a, opacity=0.8),
                 go.Histogram(x=x_b, opacity=0.8)])
fig.update_layout(barmode="overlay")

### Оценка критерия на данных

In [58]:
alpha = 0.05

In [59]:
p_values[p_values < alpha].shape[0] / p_values.shape[0]

0.0506

In [60]:
probs = []
x = [0.01 * i for i in range(101)]
for i in range(101):
    alpha_step = 0.01 * i
    probs.append(p_values[p_values < alpha_step].shape[0] / p_values.shape[0])

In [61]:
fig = go.Figure([go.Scatter(x=x, y=probs, mode="markers", name="p_value"),
                 go.Scatter(x=x, y=x, mode="lines", name="uniform")])
fig.update_layout(height=600, width=600, title="Q-Q plot")

In [62]:
fig = go.Figure([go.Histogram(x=p_values, xbins={"start":0, "end":1, "size": 0.1})])
fig